import type { IconType } from "react-icons";
import {
  FaApple,
  FaBatteryEmpty,
  FaBatteryFull,
  FaBatteryHalf,
  FaBatteryQuarter,
  FaBatteryThreeQuarters,
  FaBluetooth,
  FaCloud,
  FaGitAlt,
  FaLinux,
  FaShareAlt,
  FaSnowflake,
  FaWindows,
} from "react-icons/fa";
import {
  FaDiscord,
  FaFacebook,
  FaFilter,
  FaGithub,
  FaGolang,
  FaInstagram,
  FaLinkedin,
  FaPinterest,
  FaReact,
  FaReddit,
  FaRegSun,
  FaRust,
  FaTelegram,
  FaThreads,
  FaTrophy,
  FaVuejs,
  FaWhatsapp,
  FaX,
  FaXTwitter,
} from "react-icons/fa6";
import {
  HiArrowRight,
  HiArrowTopRightOnSquare,
  HiArrowUpRight,
  HiCalendarDays,
  HiEnvelope,
  HiOutlineDocument,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineLink,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";
import {
  IoIosBatteryCharging,
  IoIosCloudy,
  IoIosCloudyNight,
  IoIosRainy,
  IoIosSunny,
  IoMdClose,
  IoMdPartlySunny,
  IoMdSend,
  IoMdTime,
} from "react-icons/io";
import {
  MdBluetoothDisabled,
  MdFoggy,
  MdNightsStay,
  MdOutlineCancel,
  MdThunderstorm,
} from "react-icons/md";
import {
  PiBookBookmarkDuotone,
  PiGridFourDuotone,
  PiHouseDuotone,
  PiImageDuotone,
  PiUserCircleDuotone,
} from "react-icons/pi";
import { RiEnglishInput } from "react-icons/ri";
import {
  SiDrizzle,
  SiFigma,
  SiGnubash,
  SiJavascript,
  SiNextdotjs,
  SiNixos,
  SiSupabase,
  SiTypescript,
  SiVim,
} from "react-icons/si";
import { TbLanguageHiragana } from "react-icons/tb";

export const iconLibrary = {
  apple: FaApple,
  bluetooth: FaBluetooth,
  batteryFull: FaBatteryFull,
  batteryEmpty: FaBatteryEmpty,
  batteryQuarter: FaBatteryQuarter,
  batteryHalf: FaBatteryHalf,
  batteryThreeQuarters: FaBatteryThreeQuarters,
  batteryCharging: IoIosBatteryCharging,
  bluetoothDisabled: MdBluetoothDisabled,
  windows: FaWindows,
  linux: FaLinux,
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  bash: SiGnubash,
  cloud: FaCloud,
  close: IoMdClose,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  filter: FaFilter,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  git: FaGitAlt,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  trophy: FaTrophy,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  typescript: SiTypescript,
  rust: FaRust,
  send: IoMdSend,
  goLang: FaGolang,
  vuejs: FaVuejs,
  vim: SiVim,
  nixOs: SiNixos,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  time: IoMdTime,
  instagram: FaInstagram,
  sun: FaRegSun,
  ioiosSunny: IoIosSunny,
  react: FaReact,
  share: FaShareAlt,
  outlineCancel: MdOutlineCancel,
  languageHiragana: TbLanguageHiragana,
  englishInput: RiEnglishInput,
  //Weather Specific Icons
  cloudy: IoIosCloudy,
  cloudyDay: IoMdPartlySunny,
  cloudyNight: IoIosCloudyNight,
  clearDay: IoIosSunny,
  clearNight: MdNightsStay,
  foggy: MdFoggy,
  rainy: IoIosRainy,
  thunderstorm: MdThunderstorm,
  snowflake: FaSnowflake,
  drizzle: SiDrizzle,
} as const satisfies Record<string, IconType>;

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
